// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplicationAPP.Models;

#nullable disable

namespace WebApplicationAPP.Migrations
{
    [DbContext(typeof(YampiBarbershopContext))]
    [Migration("20260722022542_AgregarCampoCerradoPago")]
    partial class AgregarCampoCerradoPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RolesPrivilegio", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPrivilegio")
                        .HasColumnType("int")
                        .HasColumnName("id_privilegio");

                    b.HasKey("IdRol", "IdPrivilegio")
                        .HasName("PK__RolesPri__BD72B641FCABBDE1");

                    b.HasIndex("IdPrivilegio");

                    b.ToTable("RolesPrivilegios", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Atencion", b =>
                {
                    b.Property<int>("IdAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_atencion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAtencion"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int?>("IdCita")
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdAtencion")
                        .HasName("PK__Atencion__D0A40236964961F9");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdCliente");

                    b.ToTable("Atencion", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.BitacoraCliente", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdBitacora")
                        .HasName("PK__Bitacora__7E4268B06328B701");

                    b.ToTable("BitacoraClientes");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.BitacoraPago", b =>
                {
                    b.Property<int>("IdBitacora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_bitacora");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBitacora"));

                    b.Property<string>("Accion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("accion");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.HasKey("IdBitacora")
                        .HasName("PK__Bitacora__7E4268B04BE8D54F");

                    b.ToTable("BitacoraPagos");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Cita", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCita"));

                    b.Property<string>("Barbero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("barbero");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdCita")
                        .HasName("PK__Citas__6AEC3C09FAA5DDFC");

                    b.HasIndex("IdCliente");

                    b.ToTable("Citas", t =>
                        {
                            t.HasTrigger("trg_EvitarCitaDuplicada");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente")
                        .HasName("PK__Clientes__677F38F5C6D7EA4B");

                    b.ToTable("Clientes", t =>
                        {
                            t.HasTrigger("trg_BitacoraClientes");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<bool>("Cerrado")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("metodo");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.HasKey("IdPago")
                        .HasName("PK__Pagos__0941B07420F56711");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pagos", t =>
                        {
                            t.HasTrigger("trg_ActualizarReporte");

                            t.HasTrigger("trg_BitacoraPagos");

                            t.HasTrigger("trg_ValidarMontoPago");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Privilegio", b =>
                {
                    b.Property<int>("IdPrivilegio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_privilegio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrivilegio"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPrivilegio")
                        .HasName("PK__Privileg__7CE03A1CC5AB2111");

                    b.ToTable("Privilegios");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Reporte", b =>
                {
                    b.Property<int>("IdReporte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reporte");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReporte"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<decimal>("IngresosTotales")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("ingresos_totales");

                    b.HasKey("IdReporte")
                        .HasName("PK__Reportes__87E4F5CBDF3BECA3");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("IdRol")
                        .HasName("PK__Roles__6ABCB5E0200EB176");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("ContraTemp")
                        .HasColumnType("bit");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("correoElectronico");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("id_rol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("IdUsuario")
                        .HasName("PK__Usuarios__4E3E04AD8BBE2F68");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Username" }, "UQ__Usuarios__F3DBC572E9920D8E")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwCitasDelDium", b =>
                {
                    b.Property<string>("Barbero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("barbero");

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<TimeOnly>("Hora")
                        .HasColumnType("time")
                        .HasColumnName("hora");

                    b.Property<int>("IdCita")
                        .HasColumnType("int")
                        .HasColumnName("id_cita");

                    b.ToTable((string)null);

                    b.ToView("vw_CitasDelDia", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwClientesFrecuente", b =>
                {
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("TotalCitas")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ClientesFrecuentes", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwEstadoAtencion", b =>
                {
                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly?>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.ToTable((string)null);

                    b.ToView("vw_EstadoAtencion", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwPagosRealizado", b =>
                {
                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<int>("IdPago")
                        .HasColumnType("int")
                        .HasColumnName("id_pago");

                    b.Property<string>("Metodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("metodo");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("monto");

                    b.ToTable((string)null);

                    b.ToView("vw_PagosRealizados", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwRolesPrivilegio", b =>
                {
                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Privilegio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.ToTable((string)null);

                    b.ToView("vw_RolesPrivilegios", (string)null);
                });

            modelBuilder.Entity("WebApplicationAPP.Models.VwUsuariosRole", b =>
                {
                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_UsuariosRoles", (string)null);
                });

            modelBuilder.Entity("RolesPrivilegio", b =>
                {
                    b.HasOne("WebApplicationAPP.Models.Privilegio", null)
                        .WithMany()
                        .HasForeignKey("IdPrivilegio")
                        .IsRequired()
                        .HasConstraintName("FK_RolesPrivilegios_Privilegios");

                    b.HasOne("WebApplicationAPP.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_RolesPrivilegios_Roles");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Atencion", b =>
                {
                    b.HasOne("WebApplicationAPP.Models.Cita", "IdCitaNavigation")
                        .WithMany("Atencions")
                        .HasForeignKey("IdCita")
                        .HasConstraintName("FK_Atencion_Citas");

                    b.HasOne("WebApplicationAPP.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Atencions")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Atencion_Clientes");

                    b.Navigation("IdCitaNavigation");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Cita", b =>
                {
                    b.HasOne("WebApplicationAPP.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Cita")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Citas_Clientes");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Pago", b =>
                {
                    b.HasOne("WebApplicationAPP.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Pagos_Clientes");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Usuario", b =>
                {
                    b.HasOne("WebApplicationAPP.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Roles");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Cita", b =>
                {
                    b.Navigation("Atencions");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Cliente", b =>
                {
                    b.Navigation("Atencions");

                    b.Navigation("Cita");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("WebApplicationAPP.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
